### PR TITLE
followup fixes related to idaholab/moose#9617

### PR DESCRIPTION
**Pull request by rwcarlsen**
yes.

### CODE REVIEW

**Comment by amjokisaari** [comment]
No, this is not correct - the n variable needs to have its initial condition set.  If that breaks the test, then I need to fix the test.

**Comment by rwcarlsen** [comment]
The parameter was being set twice - so the second was overwriting the first.

**Comment by amjokisaari** [comment]
yeah.  Don't do anything with this yet, I need to look at the test itself - I may need to correct it.

**Comment by amjokisaari** [comment]
The tests were ok (scientifically) in hyrax.  I have corrected the input files.  Closing this pull request.

**Pull request closed without merging**
